apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: wpljpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wpljpipelinesjavascriptdocker 
    spec:
      containers:
        - name: wpljpipelinesjavascriptdocker 
          image: acrdevsbrg.azurecr.io/wpljpipelinesjavascriptdocker
          ports:
          - containerPort: 8080